/**
 * Brand logo URLs mapped by service slug.
 * Logos stored in /public/logos/ (128px favicons from Google).
 * Falls back to brandColor + monogram if no logo is found.
 */

const LOGO_MAP: Record<string, string> = {
  // AI Chat
  "chatgpt-plus": "/logos/openai.png",
  "chatgpt-pro": "/logos/openai.png",
  "chatgpt-team": "/logos/openai.png",
  "claude-pro": "/logos/anthropic.png",
  "claude-max": "/logos/anthropic.png",
  "gemini-advanced": "/logos/gemini.png",
  "perplexity-pro": "/logos/perplexity.png",

  // AI Image
  "midjourney": "/logos/midjourney.png",
  "leonardo-ai": "/logos/leonardo.png",

  // AI Video
  "runway": "/logos/runwayml.png",
  "pika": "/logos/pika.png",
  "heygen": "/logos/heygen.png",
  "synthesia": "/logos/synthesia.png",
  "invideo": "/logos/invideo.png",
  "lumen5": "/logos/lumen5.png",
  "pictory": "/logos/pictory.png",

  // AI Audio
  "elevenlabs": "/logos/elevenlabs.png",
  "suno": "/logos/suno.png",

  // AI Code
  "cursor": "/logos/cursor.png",
  "github-copilot": "/logos/github.png",
  "windsurf": "/logos/codeium.png",
  "v0-dev": "/logos/vercel.png",

  // AI Writing
  "grammarly-premium": "/logos/grammarly.png",
  "jasper-ai": "/logos/jasper.png",
  "writesonic": "/logos/writesonic.png",
  "copy-ai": "/logos/copy-ai.png",
  "quillbot": "/logos/quillbot.png",
  "wordtune": "/logos/wordtune.png",
  "rytr": "/logos/rytr.png",
  "deepl": "/logos/deepl.png",

  // AI Productivity
  "notion-ai": "/logos/notion.png",

  // AI Design
  "canva-pro": "/logos/canva.png",
  "adobe-creative-cloud": "/logos/adobe.png",
  "figma-professional": "/logos/figma.png",
  "adobe-firefly": "/logos/adobe.png",
  "adobe-express": "/logos/adobe.png",
  "adobe-stock": "/logos/adobe.png",
  "adobe-premiere-pro-rush": "/logos/adobe.png",
  "adobe-podcast": "/logos/adobe.png",
  "adobe-connect": "/logos/adobe.png",
  "photoroom": "/logos/photoroom.png",
  "remove-bg": "/logos/remove-bg.png",
  "pixlr": "/logos/pixlr.png",
  "freepik": "/logos/freepik.png",

  // Stock/Assets
  "shutterstock": "/logos/shutterstock.png",
  "envato": "/logos/envato.png",
  "istock": "/logos/istock.png",
  "gettyimages": "/logos/gettyimages.png",

  // Streaming
  "netflix": "/logos/netflix.png",
  "disney-plus": "/logos/disneyplus.png",
  "hbo-max": "/logos/hbomax.png",
  "amazon-prime-video": "/logos/primevideo.png",
  "youtube-premium": "/logos/youtube.png",
  "hulu": "/logos/hulu.png",
  "paramount-plus": "/logos/paramount.png",
  "peacock": "/logos/peacock.png",
  "crunchyroll": "/logos/crunchyroll.png",
  "mubi": "/logos/mubi.png",
  "dazn": "/logos/dazn.png",
  "espn-plus": "/logos/espn.png",
  "britbox": "/logos/britbox.png",
  "starz": "/logos/starz.png",
  "hayu": "/logos/hayu.png",
  "fubo-tv": "/logos/fubo.png",
  "shudder": "/logos/shudder.png",
  "viki": "/logos/viki.png",
  "funimation": "/logos/funimation.png",
  "amc-plus": "/logos/primevideo.png",
  "acorn-tv": "/logos/primevideo.png",
  "twitch": "/logos/twitch.png",

  // Music
  "spotify-premium": "/logos/spotify.png",
  "apple-music": "/logos/apple.png",
  "tidal": "/logos/tidal.png",
  "deezer": "/logos/deezer.png",
  "soundcloud": "/logos/soundcloud.png",
  "audible": "/logos/audible.png",
  "amazon-music-unlimited": "/logos/primevideo.png",
  "amazon-kindle-unlimited": "/logos/kindle.png",

  // VPN
  "expressvpn": "/logos/expressvpn.png",
  "outline-vpn": "/logos/outline.png",
  "nordvpn": "/logos/nordvpn.png",
  "surfshark": "/logos/surfshark.png",
  "mullvad": "/logos/mullvad.png",
  "protonvpn": "/logos/proton.png",

  // Education
  "duolingo-plus": "/logos/duolingo.png",
  "coursera-plus": "/logos/coursera.png",
  "skillshare": "/logos/skillshare.png",
  "udemy": "/logos/udemy.png",

  // Tools & SaaS
  "linkedin-premium": "/logos/linkedin.png",
  "tradingview": "/logos/tradingview.png",
  "google-drive": "/logos/google.png",
  "dropbox": "/logos/dropbox.png",
  "zoom": "/logos/zoom.png",
  "slack": "/logos/slack.png",
  "todoist": "/logos/todoist.png",
  "evernote": "/logos/evernote.png",
  "1password": "/logos/1password.png",
  "lastpass": "/logos/lastpass.png",
  "loom": "/logos/loom.png",
  "calendly": "/logos/calendly.png",
  "miro": "/logos/miro.png",
  "asana": "/logos/asana.png",
  "trello": "/logos/trello.png",
  "monday": "/logos/monday.png",
  "clickup": "/logos/clickup.png",
  "hubspot": "/logos/hubspot.png",
  "mailchimp": "/logos/mailchimp.png",
  "hootsuite": "/logos/hootsuite.png",
  "buffer": "/logos/buffer.png",
  "hotjar": "/logos/hotjar.png",
  "typeform": "/logos/typeform.png",
  "docusign": "/logos/docusign.png",
  "webflow": "/logos/webflow.png",
  "shopify": "/logos/shopify.png",
  "wordpress": "/logos/wordpress.png",
  "wix": "/logos/wix.png",
  "squarespace": "/logos/squarespace.png",
  "capcut": "/logos/capcut.png",

  // Security
  "bitdefender": "/logos/bitdefender.png",
  "kaspersky": "/logos/kaspersky.png",
  "malwarebytes": "/logos/malwarebytes.png",

  // Gaming
  "steam-wallet": "/logos/steam.png",
  "xbox-game-pass": "/logos/xbox.png",
  "playstation-plus": "/logos/playstation.png",
  "roblox": "/logos/roblox.png",
  "minecraft": "/logos/minecraft.png",
  "epic-games": "/logos/epic.png",

  // Gift Cards
  "apple-gift-card": "/logos/apple.png",

  // SEO
  "semrush": "/logos/semrush.png",
  "ahrefs": "/logos/ahrefs.png",
  "moz": "/logos/moz.png",
  "buzzsumo": "/logos/buzzsumo.png",

  // Cloud/Dev
  "aws": "/logos/aws.png",
  "cloudflare": "/logos/cloudflare.png",
  "digitalocean": "/logos/digitalocean.png",
  "heroku": "/logos/heroku.png",
  "netlify": "/logos/netlify.png",
  "vercel": "/logos/vercel.png",
  "supabase": "/logos/supabase.png",
  "firebase": "/logos/firebase.png",
  "mongodb": "/logos/mongodb.png",
  "datadog": "/logos/datadog.png",
  "sentry": "/logos/sentry.png",

  // Social
  "telegram-premium": "/logos/telegram.png",
  "discord-nitro": "/logos/discord.png",
  "reddit-premium": "/logos/reddit.png",
  "snapchat-plus": "/logos/snapchat.png",
  "pinterest": "/logos/pinterest.png",
};

const DOMAIN_LOGO_MAP: Record<string, string> = {
  chatgpt: "/logos/openai.png",
  openai: "/logos/openai.png",
  claude: "/logos/anthropic.png",
  anthropic: "/logos/anthropic.png",
  gemini: "/logos/gemini.png",
  spotify: "/logos/spotify.png",
  netflix: "/logos/netflix.png",
  canva: "/logos/canva.png",
  adobe: "/logos/adobe.png",
  notion: "/logos/notion.png",
  figma: "/logos/figma.png",
  slack: "/logos/slack.png",
  zoom: "/logos/zoom.png",
  dropbox: "/logos/dropbox.png",
  grammarly: "/logos/grammarly.png",
  duolingo: "/logos/duolingo.png",
  udemy: "/logos/udemy.png",
  coursera: "/logos/coursera.png",
  linkedin: "/logos/linkedin.png",
  apple: "/logos/apple.png",
  google: "/logos/google.png",
  microsoft: "/logos/microsoft.png",
  github: "/logos/github.png",
  youtube: "/logos/youtube.png",
  steam: "/logos/steam.png",
  xbox: "/logos/xbox.png",
  playstation: "/logos/playstation.png",
  cursor: "/logos/cursor.png",
  midjourney: "/logos/midjourney.png",
  perplexity: "/logos/perplexity.png",
  semrush: "/logos/semrush.png",
  tradingview: "/logos/tradingview.png",
  elevenlabs: "/logos/elevenlabs.png",
  suno: "/logos/suno.png",
  runway: "/logos/runwayml.png",
  pika: "/logos/pika.png",
  heygen: "/logos/heygen.png",
  nord: "/logos/nordvpn.png",
  express: "/logos/expressvpn.png",
  disney: "/logos/disneyplus.png",
  telegram: "/logos/telegram.png",
  discord: "/logos/discord.png",
  whatsapp: "/logos/whatsapp.png",
  instagram: "/logos/instagram.png",
  tiktok: "/logos/tiktok.png",
  twitter: "/logos/twitter.png",
  reddit: "/logos/reddit.png",
  pinterest: "/logos/pinterest.png",
  snapchat: "/logos/snapchat.png",
  twitch: "/logos/twitch.png",
  evernote: "/logos/evernote.png",
  todoist: "/logos/todoist.png",
  "1password": "/logos/1password.png",
  lastpass: "/logos/lastpass.png",
  bitdefender: "/logos/bitdefender.png",
  kaspersky: "/logos/kaspersky.png",
  malwarebytes: "/logos/malwarebytes.png",
  surfshark: "/logos/surfshark.png",
  mullvad: "/logos/mullvad.png",
  proton: "/logos/proton.png",
  deezer: "/logos/deezer.png",
  soundcloud: "/logos/soundcloud.png",
  audible: "/logos/audible.png",
  kindle: "/logos/kindle.png",
  crunchyroll: "/logos/crunchyroll.png",
  paramount: "/logos/paramount.png",
  peacock: "/logos/peacock.png",
  hulu: "/logos/hulu.png",
  dazn: "/logos/dazn.png",
  espn: "/logos/espn.png",
  mubi: "/logos/mubi.png",
  starz: "/logos/starz.png",
  britbox: "/logos/britbox.png",
  capcut: "/logos/capcut.png",
  deepl: "/logos/deepl.png",
  quillbot: "/logos/quillbot.png",
  wordtune: "/logos/wordtune.png",
  photoroom: "/logos/photoroom.png",
  freepik: "/logos/freepik.png",
  envato: "/logos/envato.png",
  shutterstock: "/logos/shutterstock.png",
  hubspot: "/logos/hubspot.png",
  mailchimp: "/logos/mailchimp.png",
  salesforce: "/logos/salesforce.png",
  zendesk: "/logos/zendesk.png",
  asana: "/logos/asana.png",
  trello: "/logos/trello.png",
  monday: "/logos/monday.png",
  clickup: "/logos/clickup.png",
  jira: "/logos/jira.png",
  miro: "/logos/miro.png",
  loom: "/logos/loom.png",
  calendly: "/logos/calendly.png",
  typeform: "/logos/typeform.png",
  docusign: "/logos/docusign.png",
  webflow: "/logos/webflow.png",
  shopify: "/logos/shopify.png",
  wordpress: "/logos/wordpress.png",
  wix: "/logos/wix.png",
  squarespace: "/logos/squarespace.png",
  roblox: "/logos/roblox.png",
  minecraft: "/logos/minecraft.png",
  epic: "/logos/epic.png",
  aws: "/logos/aws.png",
  cloudflare: "/logos/cloudflare.png",
  firebase: "/logos/firebase.png",
  mongodb: "/logos/mongodb.png",
  datadog: "/logos/datadog.png",
  sentry: "/logos/sentry.png",
  hotjar: "/logos/hotjar.png",
  hootsuite: "/logos/hootsuite.png",
  buffer: "/logos/buffer.png",
  synthesia: "/logos/synthesia.png",
  invideo: "/logos/invideo.png",
  pictory: "/logos/pictory.png",
  lumen: "/logos/lumen5.png",
  ahrefs: "/logos/ahrefs.png",
  moz: "/logos/moz.png",
  buzzsumo: "/logos/buzzsumo.png",
  pixlr: "/logos/pixlr.png",
  filmora: "/logos/filmora.png",
  movavi: "/logos/movavi.png",
  davinci: "/logos/davinci.png",
  blender: "/logos/blender.png",
  unity: "/logos/unity.png",
  procreate: "/logos/procreate.png",
  sketch: "/logos/sketch.png",
  veo: "/logos/veo.png",
  amazon: "/logos/primevideo.png",
  hbo: "/logos/hbomax.png",
  jasper: "/logos/jasper.png",
  writesonic: "/logos/writesonic.png",
  rytr: "/logos/rytr.png",
  copy: "/logos/copy-ai.png",
  leonardo: "/logos/leonardo.png",
  fubo: "/logos/fubo.png",
  acorn: "/logos/primevideo.png",
  shudder: "/logos/shudder.png",
  hayu: "/logos/hayu.png",
  viki: "/logos/viki.png",
  tidal: "/logos/tidal.png",
};

export function getServiceLogo(slug: string, name: string): string | null {
  if (LOGO_MAP[slug]) return LOGO_MAP[slug];

  const lower = name.toLowerCase();
  for (const [key, path] of Object.entries(DOMAIN_LOGO_MAP)) {
    if (lower.includes(key)) return path;
  }

  return null;
}
