import type { Service } from "./types";
import { EXTENDED_SERVICES } from "./services-extended";

const CURATED_SERVICES: Service[] = [
  // ===== AI CHAT =====
  {
    slug: "chatgpt-plus",
    name: "ChatGPT Plus",
    nameFa: "چت جی‌پی‌تی پلاس",
    category: "ai-chat",
    shortFa: "نسخه پلاس ChatGPT با مدل GPT-5، تولید تصویر، صدا و وب",
    taglineFa: "محبوب‌ترین دستیار هوش مصنوعی جهان روی اکانت شخصی شما",
    descriptionFa:
      "اشتراک ChatGPT Plus به شما دسترسی کامل به مدل‌های جدید GPT-5، حالت پیشرفته صوتی، تولید تصویر با DALL·E و GPT Image، آپلود فایل، تحلیل داده و وب‌گردی زنده می‌دهد. اشتراک روی ایمیل شخصی شما فعال می‌شود و در همه دستگاه‌ها قابل استفاده است.",
    features: [
      "دسترسی به GPT-5 و مدل‌های جدید",
      "تولید تصویر با DALL·E و GPT Image",
      "حالت صوتی پیشرفته (Advanced Voice)",
      "آپلود فایل و تحلیل داده",
      "وب‌گردی زنده و سرچ",
      "ساخت GPT اختصاصی",
    ],
    tariffs: [
      { name: "اشتراک یک‌ماهه", period: "۳۰ روز", priceUsd: 25, popular: true },
      { name: "اشتراک سه‌ماهه", period: "۹۰ روز", priceUsd: 70, oldPriceUsd: 75 },
      { name: "اشتراک یک‌ساله", period: "۳۶۵ روز", priceUsd: 240, oldPriceUsd: 300 },
    ],
    brandColor: "#0d6f6a",
    monogram: "GPT",
    bestseller: true,
    popular: true,
    region: "Global",
    faq: [
      {
        q: "آیا اشتراک روی اکانت خودم فعال می‌شود؟",
        a: "بله. شما ایمیل اکانت OpenAI خود را می‌دهید و ما فقط اشتراک را فعال می‌کنیم. پسورد یا اطلاعات حساس نیاز نداریم.",
      },
      {
        q: "آیا برای استفاده در ایران به وی‌پی‌ان نیاز دارم؟",
        a: "بله، برای دسترسی به ChatGPT از داخل ایران به وی‌پی‌ان نیاز دارید. ما کانفیگ‌های مخصوص ایران هم می‌فروشیم که با ChatGPT کار می‌کنند.",
      },
      {
        q: "پرداخت با تتر (USDT) ممکن است؟",
        a: "بله، پرداخت با تتر روی شبکه‌های TRC-20 و TON و BEP-20 پذیرفته می‌شود.",
      },
    ],
  },
  {
    slug: "chatgpt-pro",
    name: "ChatGPT Pro",
    nameFa: "چت جی‌پی‌تی پرو",
    category: "ai-chat",
    shortFa: "حداکثر دسترسی به GPT-5 Pro، o1 Pro و Sora",
    taglineFa: "نسخه پرو برای کاربران حرفه‌ای و توسعه‌دهنده",
    descriptionFa:
      "ChatGPT Pro نسخه پیشرفته OpenAI است که شامل دسترسی نامحدود به GPT-5، حالت o1 Pro برای استدلال عمیق، تولید ویدیو با Sora و حالت صوتی نامحدود می‌شود. مناسب برای محققان، توسعه‌دهندگان و کاربرانی که هر روز ساعت‌ها با AI کار می‌کنند.",
    features: [
      "دسترسی نامحدود به GPT-5 و o1 Pro",
      "حالت استدلال عمیق Pro Mode",
      "تولید ویدیو با Sora",
      "حالت صوتی نامحدود",
      "اولویت در دسترسی به مدل‌های جدید",
    ],
    tariffs: [
      { name: "اشتراک یک‌ماهه", period: "۳۰ روز", priceUsd: 220, popular: true },
      { name: "اشتراک سه‌ماهه", period: "۹۰ روز", priceUsd: 630 },
    ],
    brandColor: "#093d3a",
    monogram: "PRO",
    region: "Global",
  },
  {
    slug: "chatgpt-team",
    name: "ChatGPT Team",
    nameFa: "چت جی‌پی‌تی تیم",
    category: "ai-chat",
    shortFa: "نسخه تیمی با محدودیت بالاتر و فضای کاری مشترک",
    taglineFa: "برای تیم‌ها و کسب‌وکارهای کوچک",
    descriptionFa:
      "نسخه Team برای استارتاپ‌ها و تیم‌های کاری مناسب است. هر کاربر اشتراک کامل دارد و امکان مدیریت تیم، فضای کاری مشترک و GPT اختصاصی تیم در اختیار شماست. داده‌های شما برای آموزش مدل استفاده نمی‌شود.",
    features: [
      "اشتراک کامل برای هر عضو تیم",
      "فضای کاری مشترک GPT",
      "محدودیت پیام بالاتر از Plus",
      "بدون استفاده از داده شما برای آموزش",
      "مدیریت متمرکز اعضا",
    ],
    tariffs: [
      { name: "اشتراک ۲ نفره ماهانه", period: "۳۰ روز", priceUsd: 70 },
      { name: "اشتراک ۲ نفره سالانه", period: "۳۶۵ روز", priceUsd: 700, popular: true },
    ],
    brandColor: "#0d6f6a",
    monogram: "TEAM",
    region: "Global",
  },
  {
    slug: "claude-pro",
    name: "Claude Pro",
    nameFa: "کلود پرو",
    category: "ai-chat",
    shortFa: "هوش مصنوعی Anthropic با مدل Claude 4 Sonnet و Opus",
    taglineFa: "بهترین گزینه برای نوشتن متن طولانی و کدنویسی",
    descriptionFa:
      "Claude Pro از شرکت Anthropic یکی از قوی‌ترین مدل‌های زبانی است که در درک متن طولانی، کدنویسی و تحلیل اسناد عالی عمل می‌کند. اشتراک شامل دسترسی به Claude 4 Sonnet و Opus، حالت Projects، Artifacts و Computer Use می‌شود.",
    features: [
      "Claude 4 Sonnet و Opus",
      "حافظه پروژه (Projects)",
      "Artifacts برای کد و طراحی",
      "آپلود اسناد و تحلیل PDF",
      "محدودیت پیام بالاتر",
    ],
    tariffs: [
      { name: "اشتراک یک‌ماهه", period: "۳۰ روز", priceUsd: 25, popular: true },
      { name: "اشتراک سه‌ماهه", period: "۹۰ روز", priceUsd: 70 },
      { name: "اشتراک یک‌ساله", period: "۳۶۵ روز", priceUsd: 240, oldPriceUsd: 300 },
    ],
    brandColor: "#c0653a",
    monogram: "CL",
    bestseller: true,
    popular: true,
    region: "Global",
  },
  {
    slug: "claude-max",
    name: "Claude Max",
    nameFa: "کلود مکس",
    category: "ai-chat",
    shortFa: "بالاترین حد استفاده از Claude Opus و Sonnet",
    taglineFa: "برای کاربران سنگین Claude",
    descriptionFa:
      "Claude Max برای کسانی است که هر روز چندین ساعت با Claude کار می‌کنند. محدودیت پیام تا ۲۰ برابر Pro و دسترسی اولویت‌دار به مدل‌های جدید مثل Opus 4.1 ارائه می‌دهد.",
    features: [
      "حد پیام تا ۵ یا ۲۰ برابر Pro",
      "Claude Opus 4.1 با اولویت",
      "Computer Use",
      "کدنویسی Claude Code",
    ],
    tariffs: [
      { name: "Max ۵x ماهانه", period: "۳۰ روز", priceUsd: 110 },
      { name: "Max ۲۰x ماهانه", period: "۳۰ روز", priceUsd: 220, popular: true },
    ],
    brandColor: "#a8542a",
    monogram: "MAX",
    region: "Global",
  },
  {
    slug: "gemini-advanced",
    name: "Gemini Advanced",
    nameFa: "جمنای ادونسد",
    category: "ai-chat",
    shortFa: "هوش مصنوعی گوگل با مدل Gemini 2.5 Pro و Veo",
    taglineFa: "تجربه AI گوگل با ۲ ترابایت فضای ذخیره‌سازی",
    descriptionFa:
      "Google AI Pro (که قبلاً Gemini Advanced نام داشت) شامل مدل پیشرفته Gemini 2.5 Pro، تولید ویدیو با Veo 3، NotebookLM Plus، Whisk، یکپارچگی با Gmail و Docs و ۲ ترابایت فضای ذخیره‌سازی Google One است.",
    features: [
      "Gemini 2.5 Pro و Deep Research",
      "تولید ویدیو با Veo 3",
      "NotebookLM Plus",
      "ادغام با Gmail و Docs",
      "۲TB فضای Google One",
    ],
    tariffs: [
      { name: "اشتراک یک‌ماهه", period: "۳۰ روز", priceUsd: 25 },
      { name: "اشتراک سه‌ماهه", period: "۹۰ روز", priceUsd: 70, popular: true },
      { name: "اشتراک یک‌ساله", period: "۳۶۵ روز", priceUsd: 240 },
    ],
    brandColor: "#1a73c7",
    monogram: "Gm",
    popular: true,
    region: "Global",
  },
  {
    slug: "perplexity-pro",
    name: "Perplexity Pro",
    nameFa: "پرپلکسیتی پرو",
    category: "ai-chat",
    shortFa: "موتور جستجوی هوشمند با منبع‌دهی دقیق",
    taglineFa: "جستجوی هوش مصنوعی برای محققان و دانشجویان",
    descriptionFa:
      "Perplexity Pro یک موتور جستجوی AI است که برخلاف ChatGPT همیشه به منابع واقعی لینک می‌دهد. مناسب تحقیقات دانشگاهی، رصد بازار و یافتن سریع اطلاعات. شامل دسترسی به مدل‌های GPT-5، Claude 4، Gemini 2.5 و Sonar Pro.",
    features: [
      "جستجوی هوشمند با منابع",
      "دسترسی به GPT-5، Claude 4، Sonar",
      "Spaces برای پروژه‌ها",
      "آپلود فایل",
      "تولید تصویر",
    ],
    tariffs: [
      { name: "اشتراک یک‌ماهه", period: "۳۰ روز", priceUsd: 22 },
      { name: "اشتراک یک‌ساله", period: "۳۶۵ روز", priceUsd: 199, popular: true, oldPriceUsd: 264 },
    ],
    brandColor: "#1a8a8a",
    monogram: "Px",
    bestseller: true,
    region: "Global",
  },
  {
    slug: "grok-supergrok",
    name: "SuperGrok",
    nameFa: "سوپر گراک",
    category: "ai-chat",
    shortFa: "هوش مصنوعی xAI ایلان ماسک با مدل Grok 4",
    taglineFa: "Grok با حالت Heavy و دسترسی نامحدود",
    descriptionFa:
      "SuperGrok نسخه پیشرفته دستیار هوش مصنوعی xAI شرکت ایلان ماسک است. شامل Grok 4، Heavy Mode برای استدلال عمیق، تولید تصویر و ویدیو و دسترسی بدون فیلتر به اطلاعات لحظه‌ای X (توییتر).",
    features: [
      "Grok 4 و Heavy Mode",
      "تولید تصویر با Aurora",
      "تولید ویدیو",
      "دسترسی به دیتای زنده X",
    ],
    tariffs: [
      { name: "SuperGrok ماهانه", period: "۳۰ روز", priceUsd: 35 },
      { name: "SuperGrok Heavy ماهانه", period: "۳۰ روز", priceUsd: 320, popular: true },
    ],
    brandColor: "#1a1a1a",
    monogram: "X",
    region: "Global",
  },
  {
    slug: "mistral-le-chat-pro",
    name: "Le Chat Pro",
    nameFa: "لِشَت پرو",
    category: "ai-chat",
    shortFa: "دستیار اروپایی Mistral با مدل Large 2",
    taglineFa: "هوش مصنوعی فرانسوی، سریع و حرفه‌ای",
    descriptionFa:
      "Le Chat Pro از شرکت فرانسوی Mistral AI، یک دستیار سریع و کم‌مصرف با تمرکز روی حریم خصوصی است. شامل Mistral Large، Codestral، تولید تصویر Flux Pro و حالت Cantine.",
    features: [
      "Mistral Large و Codestral",
      "تولید تصویر Flux Pro",
      "سرعت بالا",
      "تمرکز روی حریم خصوصی",
    ],
    tariffs: [{ name: "اشتراک ماهانه", period: "۳۰ روز", priceUsd: 18, popular: true }],
    brandColor: "#fa8a3a",
    monogram: "Mi",
    region: "Global",
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    nameFa: "دیپ‌سیک",
    category: "ai-chat",
    shortFa: "مدل قدرتمند چینی با هزینه پایین",
    taglineFa: "DeepSeek-V3 با شارژ API دلاری",
    descriptionFa:
      "DeepSeek یکی از قدرتمندترین مدل‌های منبع‌باز چینی است. ما برای شما حساب API با شارژ دلاری فعال می‌کنیم تا بتوانید با هزینه بسیار پایین از این مدل در پروژه‌هایتان استفاده کنید.",
    features: [
      "مدل DeepSeek-V3 و R1",
      "شارژ API به صورت دلاری",
      "هزینه ۱۰ برابر کمتر از GPT-5",
      "مناسب کدنویسی و ریاضیات",
    ],
    tariffs: [
      { name: "شارژ API ۲۰ دلار", period: "بدون انقضا", priceUsd: 28 },
      { name: "شارژ API ۵۰ دلار", period: "بدون انقضا", priceUsd: 65, popular: true },
      { name: "شارژ API ۱۰۰ دلار", period: "بدون انقضا", priceUsd: 125 },
    ],
    brandColor: "#3a5fb8",
    monogram: "DS",
    region: "Global",
  },

  // ===== AI IMAGE =====
  {
    slug: "midjourney",
    name: "Midjourney",
    nameFa: "میدجرنی",
    category: "ai-image",
    shortFa: "محبوب‌ترین سرویس تولید تصویر هنری",
    taglineFa: "کیفیت تصویر بی‌رقیب، استایل سینمایی",
    descriptionFa:
      "Midjourney استاندارد طلایی تولید تصویر AI است. اشتراک روی اکانت شخصی شما فعال می‌شود و امکان استفاده هم در دیسکورد و هم در وب‌سایت رسمی Midjourney را دارید. مناسب طراحان، تصویرگران و سازندگان محتوا.",
    features: [
      "تولید تصویر با کیفیت بی‌نظیر",
      "حالت ویدیو با Midjourney V1",
      "حالت Stealth برای خصوصی‌سازی",
      "استفاده در دیسکورد و وب",
      "استایل‌های اختصاصی",
    ],
    tariffs: [
      { name: "Basic ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Standard ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 75 },
      { name: "Mega ماهانه", period: "۳۰ روز", priceUsd: 145 },
    ],
    brandColor: "#1a1a2a",
    monogram: "MJ",
    bestseller: true,
    popular: true,
    region: "Global",
  },
  {
    slug: "leonardo-ai",
    name: "Leonardo AI",
    nameFa: "لئوناردو ای‌آی",
    category: "ai-image",
    shortFa: "ابزار تولید تصویر و ویدیو با مدل‌های متنوع",
    taglineFa: "مناسب گیم‌دیزاینرها و طراحان کانسپت",
    descriptionFa:
      "Leonardo AI ابزار قدرتمندی برای ساخت کانسپت آرت، تصویرسازی بازی، آواتار و حتی ویدیو است. شامل مدل‌های اختصاصی Phoenix، PhotoReal و قابلیت آموزش مدل اختصاصی روی استایل خودتان.",
    features: [
      "مدل‌های Phoenix و PhotoReal",
      "آموزش مدل اختصاصی",
      "تولید ویدیو Motion 2.0",
      "ابزار Canvas برای ادیت",
    ],
    tariffs: [
      { name: "Apprentice ماهانه", period: "۳۰ روز", priceUsd: 16 },
      { name: "Artisan ماهانه", period: "۳۰ روز", priceUsd: 30, popular: true },
      { name: "Maestro ماهانه", period: "۳۰ روز", priceUsd: 60 },
    ],
    brandColor: "#5a3a8a",
    monogram: "Lo",
    region: "Global",
  },
  {
    slug: "ideogram",
    name: "Ideogram",
    nameFa: "آیدیوگرام",
    category: "ai-image",
    shortFa: "بهترین سرویس برای تصاویر با متن دقیق",
    taglineFa: "ساخت پوستر، لوگو و تایپوگرافی AI",
    descriptionFa:
      "Ideogram تخصص ویژه‌ای در درج صحیح متن داخل تصویر دارد و برای ساخت پوستر، طراحی لوگو و تایپوگرافی هنری بهترین گزینه است. اشتراک Plus امکان حذف واترمارک و کیفیت بالاتر می‌دهد.",
    features: [
      "تایپوگرافی دقیق در تصویر",
      "بدون واترمارک",
      "Magic Prompt",
      "تولید Batch",
    ],
    tariffs: [
      { name: "Plus ماهانه", period: "۳۰ روز", priceUsd: 12, popular: true },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 28 },
    ],
    brandColor: "#ea4d8b",
    monogram: "Id",
    region: "Global",
  },
  {
    slug: "flux-pro",
    name: "Flux Pro",
    nameFa: "فلاکس پرو",
    category: "ai-image",
    shortFa: "مدل آلمانی Black Forest Labs، رقیب Midjourney",
    taglineFa: "کیفیت فوتو-ریالیستیک حیرت‌انگیز",
    descriptionFa:
      "Flux از تیم سازندگان Stable Diffusion، یکی از واقع‌گرایانه‌ترین مدل‌های تصویر AI است. ما دسترسی API و وب‌اینترفیس Flux Pro را فراهم می‌کنیم.",
    features: [
      "Flux 1.1 Pro Ultra",
      "کیفیت فوتو-ریالیستیک",
      "API و وب",
      "بدون سانسور",
    ],
    tariffs: [
      { name: "بسته ۱۰۰۰ تصویر", period: "بدون انقضا", priceUsd: 25 },
      { name: "بسته ۵۰۰۰ تصویر", period: "بدون انقضا", priceUsd: 110, popular: true },
    ],
    brandColor: "#1a2a3a",
    monogram: "Fx",
    region: "Global",
  },
  {
    slug: "krea-ai",
    name: "Krea AI",
    nameFa: "کریا",
    category: "ai-image",
    shortFa: "تولید تصویر و ویدیو با حالت Real-time",
    taglineFa: "خلق سریع با کنترل کامل کانوا",
    descriptionFa:
      "Krea یکی از مدرن‌ترین رابط‌های تولید تصویر AI است که حالت Real-time و ابزارهای ادیت پیشرفته دارد. شامل دسترسی به Flux، Krea-1 و Wan 2.5.",
    features: [
      "حالت Real-time",
      "Krea-1 و Flux",
      "ادیت ویدیو",
      "آموزش مدل اختصاصی",
    ],
    tariffs: [
      { name: "Basic ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
    ],
    brandColor: "#0a0a0a",
    monogram: "Kr",
    region: "Global",
  },
  {
    slug: "recraft",
    name: "Recraft",
    nameFa: "ریکرفت",
    category: "ai-image",
    shortFa: "تولید وکتور و آیکون با AI",
    taglineFa: "بهترین گزینه برای طراحان گرافیک",
    descriptionFa:
      "Recraft یکی از معدود ابزارهای AI است که خروجی وکتور SVG با کیفیت تجاری ارائه می‌دهد. مناسب ساخت آیکون، لوگو و تصویرسازی برند.",
    features: [
      "خروجی SVG وکتور",
      "ساخت آیکون و لوگو",
      "حفظ هویت برند",
      "Recraft V3 Raw",
    ],
    tariffs: [
      { name: "Basic ماهانه", period: "۳۰ روز", priceUsd: 16, popular: true },
      { name: "Advanced ماهانه", period: "۳۰ روز", priceUsd: 38 },
    ],
    brandColor: "#fa6a3a",
    monogram: "Rc",
    region: "Global",
  },
  {
    slug: "playground-ai",
    name: "Playground AI",
    nameFa: "پلی‌گراند",
    category: "ai-image",
    shortFa: "تولید تصویر و ادیت با مدل‌های متنوع",
    taglineFa: "ابزار ادیت و کانوای پیشرفته",
    descriptionFa:
      "Playground ترکیبی از کانوای ادیت و موتور تولید AI است. مناسب کسانی که می‌خواهند فراتر از prompt، روی تصویر کنترل دقیق داشته باشند.",
    features: ["مدل Playground V3", "حالت کانوا", "ادیت پیشرفته", "Mix"],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 18 },
      { name: "Pro Plus ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
    ],
    brandColor: "#3a3a8a",
    monogram: "Pl",
    region: "Global",
  },

  // ===== AI VIDEO =====
  {
    slug: "runway",
    name: "Runway",
    nameFa: "رانوی",
    category: "ai-video",
    shortFa: "پیشرفته‌ترین ابزار ساخت ویدیو با AI",
    taglineFa: "Gen-4 Turbo، Act-One، تبدیل تصویر به ویدیو",
    descriptionFa:
      "Runway مرجع تولید ویدیو با هوش مصنوعی است. مدل Gen-4 آن می‌تواند ویدیوهای واقع‌گرایانه با کنترل کامل بسازد. اشتراک شامل Act-One برای انیمیشن چهره و Frames برای تصویر است.",
    features: [
      "Gen-4 Turbo و Aleph",
      "Act-One برای انیمیشن",
      "Image to Video",
      "ادیت ویدیو AI",
    ],
    tariffs: [
      { name: "Standard ماهانه", period: "۳۰ روز", priceUsd: 18 },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
      { name: "Unlimited ماهانه", period: "۳۰ روز", priceUsd: 99 },
    ],
    brandColor: "#0a0a0a",
    monogram: "Rw",
    bestseller: true,
    region: "Global",
  },
  {
    slug: "pika-labs",
    name: "Pika",
    nameFa: "پیکا",
    category: "ai-video",
    shortFa: "ساخت ویدیو خلاقانه با افکت‌های ویژه",
    taglineFa: "ساده، سریع و سرگرم‌کننده",
    descriptionFa:
      "Pika یکی از مدرن‌ترین ابزارهای ویدیو AI با تمرکز بر افکت‌های خلاقانه (Pikaffects) است. مناسب سازندگان محتوای شبکه‌های اجتماعی که سرعت و سادگی برایشان مهم است.",
    features: ["Pika 2.2", "Pikaffects", "Sound generation", "Lip sync"],
    tariffs: [
      { name: "Standard ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
    ],
    brandColor: "#fa3a8a",
    monogram: "Pk",
    region: "Global",
  },
  {
    slug: "luma-dream-machine",
    name: "Luma Dream Machine",
    nameFa: "لوما دریم ماشین",
    category: "ai-video",
    shortFa: "تبدیل متن یا تصویر به ویدیو",
    taglineFa: "حرکات سینمایی واقع‌گرایانه",
    descriptionFa:
      "Luma Dream Machine با مدل Ray2 می‌تواند ویدیوهایی با حرکت دوربین سینمایی و فیزیک واقع‌گرایانه تولید کند. مناسب فیلمسازان مستقل و کارگردانان.",
    features: ["مدل Ray2", "Camera Motion", "Image to Video", "Modify Mode"],
    tariffs: [
      { name: "Lite ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Plus ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
    ],
    brandColor: "#0a3a8a",
    monogram: "Lu",
    region: "Global",
  },
  {
    slug: "kling-ai",
    name: "Kling AI",
    nameFa: "کلینگ",
    category: "ai-video",
    shortFa: "مدل قدرتمند چینی برای ویدیو واقع‌گرایانه",
    taglineFa: "Kling 2.0، رقیب اصلی Sora",
    descriptionFa:
      "Kling AI یکی از باکیفیت‌ترین مدل‌های ویدیو AI جهان است. ساخت ویدیوهای ۱۰ ثانیه‌ای با Kling 2.0 Master، حالت Lip Sync و Motion Brush از قابلیت‌های آن است.",
    features: ["Kling 2.0 Master", "Motion Brush", "Lip Sync", "ویدیو ۱۰ ثانیه"],
    tariffs: [
      { name: "Standard ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 35, popular: true },
      { name: "Premier ماهانه", period: "۳۰ روز", priceUsd: 75 },
    ],
    brandColor: "#1a4a6e",
    monogram: "Kl",
    region: "Global",
  },
  {
    slug: "heygen",
    name: "HeyGen",
    nameFa: "هی‌جن",
    category: "ai-video",
    shortFa: "آواتار و دوبله ویدیو با AI",
    taglineFa: "ساخت ویدیو با اوینتر آواتار خود شما",
    descriptionFa:
      "HeyGen برای ساخت ویدیوهای آموزشی، تبلیغاتی و داخلی شرکت با آواتار AI طراحی شده. می‌توانید آواتار شخصی خودتان را بسازید و به ۱۷۵+ زبان صحبت کنید.",
    features: [
      "آواتار شخصی شما",
      "ترجمه ویدیو به ۱۷۵ زبان",
      "Lip Sync پیشرفته",
      "Video Translate",
    ],
    tariffs: [
      { name: "Creator ماهانه", period: "۳۰ روز", priceUsd: 32 },
      { name: "Team ماهانه", period: "۳۰ روز", priceUsd: 75, popular: true },
    ],
    brandColor: "#4a3aea",
    monogram: "Hy",
    popular: true,
    region: "Global",
  },
  {
    slug: "sora",
    name: "Sora",
    nameFa: "سورا",
    category: "ai-video",
    shortFa: "مدل ویدیو OpenAI، در دسترس از طریق ChatGPT Pro",
    taglineFa: "ساخت ویدیو ۲۰ ثانیه با کیفیت ۱۰۸۰p",
    descriptionFa:
      "Sora از OpenAI یکی از باکیفیت‌ترین مدل‌های ویدیو جهان است. دسترسی به Sora از طریق اشتراک ChatGPT Plus (محدود) یا ChatGPT Pro (نامحدود) ممکن است.",
    features: [
      "ویدیو تا ۲۰ ثانیه ۱۰۸۰p",
      "Storyboard",
      "Remix و Re-cut",
      "Loop و Blend",
    ],
    tariffs: [
      { name: "از طریق ChatGPT Plus", period: "۳۰ روز", priceUsd: 25 },
      { name: "از طریق ChatGPT Pro", period: "۳۰ روز", priceUsd: 220, popular: true },
    ],
    brandColor: "#0a0a0a",
    monogram: "So",
    region: "Global",
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    nameFa: "سینتزیا",
    category: "ai-video",
    shortFa: "ساخت ویدیو شرکتی با آواتار",
    taglineFa: "محبوب‌ترین ابزار ویدیو B2B",
    descriptionFa:
      "Synthesia استاندارد طلایی ساخت ویدیو آموزشی شرکتی است. آواتارهای فوق واقع‌گرایانه به ۱۴۰+ زبان صحبت می‌کنند.",
    features: ["آواتار حرفه‌ای", "۱۴۰+ زبان", "Brand Kit", "API"],
    tariffs: [
      { name: "Starter ماهانه", period: "۳۰ روز", priceUsd: 32 },
      { name: "Creator ماهانه", period: "۳۰ روز", priceUsd: 75, popular: true },
    ],
    brandColor: "#fa3a3a",
    monogram: "Sy",
    region: "Global",
  },

  // ===== AI AUDIO =====
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    nameFa: "الون‌لبز",
    category: "ai-audio",
    shortFa: "بهترین ابزار تولید صدا و دوبله AI",
    taglineFa: "صدای واقعی انسان، با هر زبان",
    descriptionFa:
      "ElevenLabs استاندارد طلایی Text-to-Speech و کلون صدا است. می‌توانید صدای خودتان را کلون کنید و به فارسی، انگلیسی و ۲۹ زبان دیگر مطلب بسازید.",
    features: [
      "کلون صدای شما",
      "بیش از ۳۰ زبان شامل فارسی",
      "Voice Design",
      "Studio برای پادکست",
      "Conversational AI",
    ],
    tariffs: [
      { name: "Starter ماهانه", period: "۳۰ روز", priceUsd: 8 },
      { name: "Creator ماهانه", period: "۳۰ روز", priceUsd: 28, popular: true },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 110 },
    ],
    brandColor: "#0a0a0a",
    monogram: "EL",
    bestseller: true,
    popular: true,
    region: "Global",
  },
  {
    slug: "suno",
    name: "Suno",
    nameFa: "سونو",
    category: "ai-audio",
    shortFa: "ساخت آهنگ کامل با AI",
    taglineFa: "ترانه با وکال، ساز و میکس حرفه‌ای",
    descriptionFa:
      "Suno محبوب‌ترین ابزار ساخت آهنگ AI است. متن ترانه می‌نویسید (یا ChatGPT می‌نویسد) و Suno یک ترک کامل با وکال، ساز و میکس می‌سازد. شامل مدل V5 جدید.",
    features: ["مدل Suno V5", "ترانه با وکال فارسی", "حالت ریمیکس", "Stems"],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 14, popular: true },
      { name: "Premier ماهانه", period: "۳۰ روز", priceUsd: 35 },
    ],
    brandColor: "#000000",
    monogram: "Su",
    bestseller: true,
    region: "Global",
  },
  {
    slug: "udio",
    name: "Udio",
    nameFa: "اودیو",
    category: "ai-audio",
    shortFa: "رقیب Suno با کیفیت موسیقی بالا",
    taglineFa: "تولید آهنگ با جزئیات سازی بیشتر",
    descriptionFa:
      "Udio از تیم سازندگان Google DeepMind، روی کیفیت سازی و میکس تمرکز دارد. مناسب موزیسین‌ها و تهیه‌کنندگان.",
    features: ["Udio v1.5 Allegro", "Stems", "ریمیکس", "Extension"],
    tariffs: [
      { name: "Standard ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 35, popular: true },
    ],
    brandColor: "#3a8aea",
    monogram: "Ud",
    region: "Global",
  },
  {
    slug: "murf",
    name: "Murf",
    nameFa: "مِرف",
    category: "ai-audio",
    shortFa: "تولید صدای پروفشنال برای ویدیو و پادکست",
    taglineFa: "Voiceover برای کسب‌وکار",
    descriptionFa:
      "Murf روی کاربرد تجاری Voiceover تمرکز دارد. صدای حرفه‌ای، تنظیم لحن، استرس و شدت در دسترس است.",
    features: ["۱۲۰+ صدا", "۲۰+ زبان", "Voice Cloning", "Voiceover Video"],
    tariffs: [
      { name: "Creator ماهانه", period: "۳۰ روز", priceUsd: 28, popular: true },
      { name: "Business ماهانه", period: "۳۰ روز", priceUsd: 85 },
    ],
    brandColor: "#fa6a3a",
    monogram: "Mu",
    region: "Global",
  },
  {
    slug: "descript",
    name: "Descript",
    nameFa: "دسکریپت",
    category: "ai-audio",
    shortFa: "ادیت ویدیو و پادکست با ویرایش متن",
    taglineFa: "Overdub، Studio Sound و Remove Filler Words",
    descriptionFa:
      "Descript ادیت پادکست و ویدیو را به سادگی ادیت کردن یک سند تبدیل می‌کند. متن را ادیت کنید، ویدیو خودش ادیت می‌شود.",
    features: ["ادیت متنی ویدیو", "Studio Sound", "Overdub", "Remove Fillers"],
    tariffs: [
      { name: "Hobbyist ماهانه", period: "۳۰ روز", priceUsd: 16 },
      { name: "Creator ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
    ],
    brandColor: "#1a4aea",
    monogram: "Ds",
    region: "Global",
  },

  // ===== AI CODE =====
  {
    slug: "cursor",
    name: "Cursor",
    nameFa: "کرسر",
    category: "ai-code",
    shortFa: "ادیتور AI-first بر پایه VS Code",
    taglineFa: "محبوب‌ترین IDE هوش مصنوعی",
    descriptionFa:
      "Cursor یک VS Code با هوش مصنوعی تعبیه‌شده است که سرعت کدنویسی شما را چند برابر می‌کند. حالت Composer، Agent و دسترسی به Claude 4 و GPT-5.",
    features: [
      "Composer برای edit چندفایلی",
      "Agent خودکار",
      "Claude 4 Sonnet و GPT-5",
      "Tab Autocomplete پیشرفته",
    ],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 25, popular: true },
      { name: "Pro سالانه", period: "۳۶۵ روز", priceUsd: 240, oldPriceUsd: 300 },
      { name: "Ultra ماهانه", period: "۳۰ روز", priceUsd: 220 },
    ],
    brandColor: "#1a1a1a",
    monogram: "Cu",
    bestseller: true,
    popular: true,
    region: "Global",
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    nameFa: "گیت‌هاب کوپایلوت",
    category: "ai-code",
    shortFa: "کوپایلوت رسمی GitHub با مدل‌های متعدد",
    taglineFa: "کدنویسی هوشمند روی VS Code، JetBrains و Vim",
    descriptionFa:
      "GitHub Copilot دستیار رسمی GitHub با دسترسی به GPT-5، Claude 4، Gemini 2.5 Pro و o3. شامل Copilot Chat، Edits و Workspace.",
    features: ["GPT-5، Claude 4، Gemini", "Copilot Chat", "Copilot Edits", "Workspace"],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 14, popular: true },
      { name: "Pro+ ماهانه", period: "۳۰ روز", priceUsd: 45 },
    ],
    brandColor: "#0a0a0a",
    monogram: "GH",
    region: "Global",
  },
  {
    slug: "windsurf",
    name: "Windsurf",
    nameFa: "ویندسرف",
    category: "ai-code",
    shortFa: "ادیتور AI با حالت Cascade",
    taglineFa: "از تیم سازندگان Codeium",
    descriptionFa:
      "Windsurf (قبلاً Codeium) ادیتور AI رقیب Cursor است که حالت Cascade برای کارهای پیچیده ارائه می‌دهد.",
    features: ["Cascade Agent", "Multi-file edit", "Memories", "Live Preview"],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 18 },
      { name: "Teams ماهانه", period: "۳۰ روز", priceUsd: 38, popular: true },
    ],
    brandColor: "#1a8a6e",
    monogram: "Ws",
    region: "Global",
  },
  {
    slug: "v0-vercel",
    name: "v0",
    nameFa: "وی‌زیرو",
    category: "ai-code",
    shortFa: "ساخت UI با AI از Vercel",
    taglineFa: "تبدیل توضیح متنی به اپ کامل React",
    descriptionFa:
      "v0 از Vercel با گرفتن یک توضیح، یک اپ کامل React + Tailwind می‌سازد. مناسب پروتوتایپ سریع و طراحی صفحات.",
    features: ["React + Tailwind", "Auto Deploy روی Vercel", "Edit با AI", "Components"],
    tariffs: [
      { name: "Premium ماهانه", period: "۳۰ روز", priceUsd: 25, popular: true },
      { name: "Team ماهانه", period: "۳۰ روز", priceUsd: 38 },
    ],
    brandColor: "#0a0a0a",
    monogram: "v0",
    region: "Global",
  },
  {
    slug: "lovable",
    name: "Lovable",
    nameFa: "لاوبل",
    category: "ai-code",
    shortFa: "ساخت اپ Full-stack با AI",
    taglineFa: "از طراحی تا دیتابیس",
    descriptionFa:
      "Lovable اپ‌های Full-stack با React، Supabase و دیتابیس می‌سازد. مناسب کارآفرین‌های بدون دانش کدنویسی.",
    features: ["Full-stack تولید", "Supabase integration", "Custom Domain", "GitHub Sync"],
    tariffs: [
      { name: "Starter ماهانه", period: "۳۰ روز", priceUsd: 25 },
      { name: "Launch ماهانه", period: "۳۰ روز", priceUsd: 60, popular: true },
    ],
    brandColor: "#fa6aea",
    monogram: "Lv",
    region: "Global",
  },
  {
    slug: "bolt-new",
    name: "Bolt.new",
    nameFa: "بولت",
    category: "ai-code",
    shortFa: "ساخت اپ کامل در مرورگر",
    taglineFa: "از StackBlitz",
    descriptionFa:
      "Bolt.new می‌تواند کامل یک اپ Node.js را در مرورگر بسازد و اجرا کند، بدون نیاز به نصب چیزی.",
    features: ["Browser Runtime", "Deploy یکپارچه", "GitHub Export", "WebContainer"],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 25 },
      { name: "Pro 50 ماهانه", period: "۳۰ روز", priceUsd: 60, popular: true },
    ],
    brandColor: "#1a1a4a",
    monogram: "Bo",
    region: "Global",
  },
  {
    slug: "replit-core",
    name: "Replit Core",
    nameFa: "ریپلیت کور",
    category: "ai-code",
    shortFa: "محیط کدنویسی کلود با Replit Agent",
    taglineFa: "از Replit Agent برای ساخت اپ کامل",
    descriptionFa:
      "Replit Core شامل دسترسی به Replit Agent برای ساخت اپ کامل با AI، فضای ابری و Deploy است.",
    features: ["Replit Agent", "Cloud IDE", "Deploy", "Database میزبان"],
    tariffs: [
      { name: "Core ماهانه", period: "۳۰ روز", priceUsd: 25, popular: true },
      { name: "Teams ماهانه", period: "۳۰ روز", priceUsd: 45 },
    ],
    brandColor: "#fa6a1a",
    monogram: "Rp",
    region: "Global",
  },

  // ===== AI PRODUCTIVITY =====
  {
    slug: "notion-ai",
    name: "Notion AI",
    nameFa: "نوشن ای‌آی",
    category: "ai-productivity",
    shortFa: "هوش مصنوعی داخل اپلیکیشن Notion",
    taglineFa: "نوشتن، خلاصه‌سازی و جستجو",
    descriptionFa:
      "Notion AI درون Notion کار می‌کند و می‌تواند یادداشت‌های شما را بنویسد، خلاصه کند، ترجمه کند و در Wiki شما جستجو کند.",
    features: ["نوشتن خودکار", "خلاصه‌سازی", "جستجوی هوشمند Q&A", "ترجمه"],
    tariffs: [
      { name: "AI Add-on ماهانه", period: "۳۰ روز", priceUsd: 14, popular: true },
      { name: "Plus + AI ماهانه", period: "۳۰ روز", priceUsd: 28 },
    ],
    brandColor: "#0a0a0a",
    monogram: "No",
    region: "Global",
  },
  {
    slug: "grammarly-premium",
    name: "Grammarly Premium",
    nameFa: "گرامرلی پریمیوم",
    category: "ai-productivity",
    shortFa: "بازخوانی و اصلاح متون انگلیسی",
    taglineFa: "اصلاح گرامر، استایل و لحن",
    descriptionFa:
      "Grammarly Premium کاملاً متن انگلیسی شما را بازخوانی می‌کند: گرامر، نگارش، لحن و استایل. مناسب کسانی که با محتوای انگلیسی کار می‌کنند.",
    features: ["اصلاح گرامر پیشرفته", "Tone Detector", "Plagiarism Checker", "Generative AI"],
    tariffs: [
      { name: "Premium ماهانه", period: "۳۰ روز", priceUsd: 18, popular: true },
      { name: "Premium سالانه", period: "۳۶۵ روز", priceUsd: 145, oldPriceUsd: 216 },
    ],
    brandColor: "#15c39a",
    monogram: "Gr",
    region: "Global",
  },
  {
    slug: "jasper-ai",
    name: "Jasper",
    nameFa: "جسپر",
    category: "ai-productivity",
    shortFa: "ابزار AI تخصصی برای بازاریابی",
    taglineFa: "محتوای برند با لحن یکپارچه",
    descriptionFa:
      "Jasper یک پلتفرم AI تخصصی برای تیم‌های بازاریابی است. شامل Brand Voice، Templates و Marketing Workflows.",
    features: ["Brand Voice", "Marketing Templates", "Knowledge Base", "Workflows"],
    tariffs: [
      { name: "Creator ماهانه", period: "۳۰ روز", priceUsd: 49, popular: true },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 75 },
    ],
    brandColor: "#fa3a4a",
    monogram: "Js",
    region: "Global",
  },
  {
    slug: "otter-ai",
    name: "Otter.ai",
    nameFa: "آتر ای‌آی",
    category: "ai-productivity",
    shortFa: "تبدیل صدا به متن خودکار",
    taglineFa: "Transcribe جلسات و گزارش‌گیری",
    descriptionFa:
      "Otter.ai جلسات Zoom، Google Meet و Teams شما را به طور خودکار transcribe می‌کند، خلاصه می‌نویسد و اکشن‌آیتم استخراج می‌کند.",
    features: ["Auto-join meetings", "خلاصه AI", "Action Items", "تشخیص گویندگان"],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 18, popular: true },
      { name: "Business ماهانه", period: "۳۰ روز", priceUsd: 38 },
    ],
    brandColor: "#3a4aea",
    monogram: "Ot",
    region: "Global",
  },

  // ===== AI DESIGN =====
  {
    slug: "adobe-creative-cloud",
    name: "Adobe Creative Cloud",
    nameFa: "ادوبی کریتیو کلود",
    category: "ai-design",
    shortFa: "بسته کامل Adobe + Firefly AI",
    taglineFa: "Photoshop، Illustrator، Premiere، Firefly",
    descriptionFa:
      "اشتراک Creative Cloud All Apps شامل Photoshop، Illustrator، Premiere Pro، After Effects، Lightroom و دسترسی به Adobe Firefly AI برای تولید تصویر و ادیت با AI است.",
    features: [
      "+۲۰ اپ Adobe",
      "Firefly AI Generative Fill",
      "۱۰۰GB فضای ابری",
      "فونت‌های Adobe",
    ],
    tariffs: [
      { name: "All Apps ماهانه", period: "۳۰ روز", priceUsd: 65, popular: true },
      { name: "All Apps سالانه", period: "۳۶۵ روز", priceUsd: 660, oldPriceUsd: 780 },
    ],
    brandColor: "#fa1a1a",
    monogram: "Ad",
    bestseller: true,
    region: "Global",
  },
  {
    slug: "canva-pro",
    name: "Canva Pro",
    nameFa: "کنوا پرو",
    category: "ai-design",
    shortFa: "طراحی گرافیک ساده با Magic Studio",
    taglineFa: "+۱۰۰ هزار تمپلیت + AI",
    descriptionFa:
      "Canva Pro دسترسی به همه تمپلیت‌ها، استوک تصاویر، فونت و ابزارهای Magic Studio AI شامل Magic Write، Magic Design و Background Remover.",
    features: ["Magic Studio AI", "Background Remover", "تمپلیت‌های Pro", "Brand Kit"],
    tariffs: [
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 14, popular: true },
      { name: "Pro سالانه", period: "۳۶۵ روز", priceUsd: 130, oldPriceUsd: 168 },
    ],
    brandColor: "#00c4cc",
    monogram: "Cv",
    region: "Global",
  },
  {
    slug: "figma-pro",
    name: "Figma Professional",
    nameFa: "فیگما پروفشنال",
    category: "ai-design",
    shortFa: "ابزار طراحی UI همکاری زنده",
    taglineFa: "Make، Sites، Slides، AI",
    descriptionFa:
      "Figma Professional شامل ویرایشگر نامحدود، Dev Mode، Variables و دسترسی به Figma AI، Make و Sites برای ساخت سایت با طراحی شما.",
    features: ["Editor نامحدود", "Dev Mode", "Figma AI", "Variables", "Make & Sites"],
    tariffs: [
      { name: "Professional ماهانه", period: "۳۰ روز", priceUsd: 18, popular: true },
      { name: "Professional سالانه", period: "۳۶۵ روز", priceUsd: 175 },
    ],
    brandColor: "#0a0a0a",
    monogram: "Fg",
    region: "Global",
  },

  // ===== AI RESEARCH =====
  {
    slug: "consensus",
    name: "Consensus",
    nameFa: "کانسنسوس",
    category: "ai-research",
    shortFa: "موتور جستجوی مقالات علمی AI",
    taglineFa: "پاسخ مبتنی بر شواهد علمی",
    descriptionFa:
      "Consensus در میان ۲۰۰ میلیون مقاله علمی جستجو می‌کند و پاسخ‌های مبتنی بر شواهد می‌دهد. مناسب پژوهشگران، دانشجویان و پزشکان.",
    features: ["جستجو در مقالات علمی", "Consensus Meter", "Quality Indicators", "Copilot"],
    tariffs: [
      { name: "Premium ماهانه", period: "۳۰ روز", priceUsd: 14, popular: true },
      { name: "Premium سالانه", period: "۳۶۵ روز", priceUsd: 110 },
    ],
    brandColor: "#1a8a8a",
    monogram: "Cs",
    region: "Global",
  },
  {
    slug: "elicit",
    name: "Elicit",
    nameFa: "الیسیت",
    category: "ai-research",
    shortFa: "دستیار پژوهش با AI",
    taglineFa: "خلاصه و استخراج داده از مقالات",
    descriptionFa:
      "Elicit برای پژوهش سیستماتیک طراحی شده. مقالات را خلاصه می‌کند، داده استخراج می‌کند و در literature review کمک می‌کند.",
    features: ["Systematic Reviews", "Data Extraction", "PDF Chat", "Workflow"],
    tariffs: [
      { name: "Plus ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 50, popular: true },
    ],
    brandColor: "#3a3a8a",
    monogram: "El",
    region: "Global",
  },

  // ===== 3D MARKETPLACE =====
  {
    slug: "sketchfab-pro",
    name: "Sketchfab Pro",
    nameFa: "اسکچ‌فب پرو",
    category: "3d-marketplace",
    shortFa: "بزرگ‌ترین مارکت‌پلیس مدل‌های ۳D",
    taglineFa: "میلیون‌ها مدل سه‌بعدی Free و Premium",
    descriptionFa:
      "Sketchfab بزرگ‌ترین وب‌سایت اشتراک‌گذاری مدل‌های سه‌بعدی است. ما هم اشتراک Pro می‌فروشیم و هم می‌توانیم هر مدلی که دیدید را برایتان بخریم و تحویل دهیم.",
    features: [
      "اشتراک Pro با آپلود ۲۰۰ مدل",
      "خرید مدل‌های پولی",
      "تحویل به ایمیل",
      "تمام فرمت‌ها (FBX, OBJ, GLB)",
    ],
    tariffs: [
      { name: "Plus ماهانه", period: "۳۰ روز", priceUsd: 14 },
      { name: "Pro ماهانه", period: "۳۰ روز", priceUsd: 22, popular: true },
      { name: "خرید تک‌مدل", period: "از روی سایت", priceUsd: 0, note: "+۲۵٪ روی قیمت اصلی" },
    ],
    brandColor: "#1aa8e0",
    monogram: "Sk",
    bestseller: true,
    region: "Global",
  },
  {
    slug: "cgtrader",
    name: "CGTrader",
    nameFa: "سی‌جی‌تریدر",
    category: "3d-marketplace",
    shortFa: "خرید مدل‌های ۳D با کیفیت پروفشنال",
    taglineFa: "+۱.۵ میلیون مدل برای بازی، فیلم و VR",
    descriptionFa:
      "CGTrader یکی از بزرگ‌ترین مارکت‌های مدل سه‌بعدی است. ما خرید مدل‌های آن را برایتان انجام می‌دهیم و فایل را تحویل می‌دهیم.",
    features: ["+۱.۵M مدل", "+۲۵٪ روی قیمت اصلی", "همه فرمت‌ها", "تحویل سریع"],
    tariffs: [{ name: "خرید تک‌مدل", period: "تحویل لحظه‌ای", priceUsd: 0, note: "قیمت + ۲۵٪", popular: true }],
    brandColor: "#1a4a6e",
    monogram: "CG",
    region: "Global",
  },
  {
    slug: "turbosquid",
    name: "TurboSquid",
    nameFa: "توربواسکوید",
    category: "3d-marketplace",
    shortFa: "مدل‌های ۳D حرفه‌ای از Shutterstock",
    taglineFa: "مرجع استودیوهای فیلم و انیمیشن",
    descriptionFa:
      "TurboSquid (متعلق به Shutterstock) سال‌هاست مرجع مدل‌های سه‌بعدی پروفشنال است. خرید از این پلتفرم با کارت ایرانی ممکن نیست؛ ما این کار را برایتان می‌کنیم.",
    features: ["+ ۱M مدل", "Editorial license", "+۲۵٪ هزینه واسطه", "تحویل سریع"],
    tariffs: [{ name: "خرید تک‌مدل", period: "تحویل لحظه‌ای", priceUsd: 0, note: "قیمت + ۲۵٪", popular: true }],
    brandColor: "#fa3a3a",
    monogram: "Tb",
    region: "Global",
  },
  {
    slug: "fab-marketplace",
    name: "Fab",
    nameFa: "فَب",
    category: "3d-marketplace",
    shortFa: "مارکت یکپارچه Epic Games",
    taglineFa: "Quixel Megascans + Unreal Marketplace",
    descriptionFa:
      "Fab مارکت‌پلیس جدید Epic Games است که Unreal Marketplace، Quixel Bridge و Sketchfab Store را یکپارچه کرده. خرید با کارت ایرانی ممکن نیست؛ ما واسطه می‌شویم.",
    features: ["Megascans", "Unreal Assets", "Sketchfab Store", "تحویل به Epic Games"],
    tariffs: [{ name: "خرید تک‌آسِت", period: "تحویل لحظه‌ای", priceUsd: 0, note: "قیمت + ۲۵٪", popular: true }],
    brandColor: "#0a0a0a",
    monogram: "Fb",
    region: "Global",
  },
  {
    slug: "blender-market",
    name: "Blender Market",
    nameFa: "بلندر مارکت",
    category: "3d-marketplace",
    shortFa: "اَدآن، متریال و آسِت برای Blender",
    taglineFa: "تخصصی‌ترین مارکت Blender",
    descriptionFa:
      "Blender Market تخصصی‌ترین فروشگاه افزونه‌ها، متریال‌ها و آسِت‌های Blender است. ما خرید را برایتان انجام می‌دهیم.",
    features: ["Add-ons", "Materials", "Models", "+۲۵٪ هزینه واسطه"],
    tariffs: [{ name: "خرید تک‌آیتم", period: "تحویل لحظه‌ای", priceUsd: 0, note: "قیمت + ۲۵٪", popular: true }],
    brandColor: "#fa6a1a",
    monogram: "Bm",
    region: "Global",
  },
  {
    slug: "daz3d",
    name: "Daz 3D",
    nameFa: "دزتری‌دی",
    category: "3d-marketplace",
    shortFa: "کاراکتر و انیمیشن سه‌بعدی",
    taglineFa: "Genesis 9 و +۲۰۰ هزار آسِت",
    descriptionFa:
      "Daz 3D تخصصی برای ساخت کاراکتر و رندر انسان سه‌بعدی است. خرید کاراکترها، لباس‌ها و پوزها از این پلتفرم را برایتان انجام می‌دهیم.",
    features: ["Characters", "Clothing", "Poses", "Genesis 9"],
    tariffs: [{ name: "خرید تک‌آیتم", period: "تحویل لحظه‌ای", priceUsd: 0, note: "قیمت + ۲۵٪", popular: true }],
    brandColor: "#fa2a4a",
    monogram: "Dz",
    region: "Global",
  },
  {
    slug: "artstation-marketplace",
    name: "ArtStation Marketplace",
    nameFa: "آرت‌استیشن",
    category: "3d-marketplace",
    shortFa: "آسِت برای کانسپت‌آرت و گیم",
    taglineFa: "Brushes، Tutorials، 3D Models",
    descriptionFa:
      "ArtStation Marketplace فروشگاه پلتفرم ArtStation است. براش، توتورال، مدل و آسِت برای آرتیست‌های دیجیتال.",
    features: ["Brushes", "Tutorials", "3D Models", "+۲۵٪ هزینه"],
    tariffs: [{ name: "خرید تک‌آیتم", period: "تحویل لحظه‌ای", priceUsd: 0, note: "قیمت + ۲۵٪", popular: true }],
    brandColor: "#1a3a8a",
    monogram: "As",
    region: "Global",
  },
  {
    slug: "unity-asset-store",
    name: "Unity Asset Store",
    nameFa: "یونیتی آسِت‌استور",
    category: "3d-marketplace",
    shortFa: "همه آسِت‌های موتور بازی Unity",
    taglineFa: "اسکریپت، شیدر، مدل، صدا",
    descriptionFa:
      "خرید از Unity Asset Store با کارت ایرانی امکان‌پذیر نیست. ما خرید را به نام شما انجام می‌دهیم و آسِت روی اکانت Unity شما می‌نشیند.",
    features: ["+۸۰هزار آسِت", "تحویل روی اکانت Unity", "+۲۵٪ هزینه واسطه"],
    tariffs: [{ name: "خرید تک‌آسِت", period: "تحویل ۱۲ ساعت", priceUsd: 0, note: "قیمت + ۲۵٪", popular: true }],
    brandColor: "#0a0a0a",
    monogram: "Un",
    region: "Global",
  },

  // ===== VPN =====
  {
    slug: "outline-vpn",
    name: "Outline VPN",
    nameFa: "اوت‌لاین",
    category: "vpn",
    shortFa: "کلید Outline اختصاصی برای ایران",
    taglineFa: "ساده، سریع و پایدار",
    descriptionFa:
      "Outline یک ابزار open source از Google Jigsaw است که برای دور زدن سانسور طراحی شده. ما کلیدهای اختصاصی روی سرورهای پرسرعت می‌فروشیم. تست‌شده روی شبکه ایران.",
    features: [
      "کلید اختصاصی شما",
      "سرورهای آلمان، هلند، آمریکا",
      "تست‌شده روی همراه‌اول و ایرانسل",
      "بدون لاگ",
      "نصب در ۳۰ ثانیه",
    ],
    tariffs: [
      { name: "یک‌ماهه ۵۰GB", period: "۳۰ روز", priceUsd: 5 },
      { name: "یک‌ماهه نامحدود", period: "۳۰ روز", priceUsd: 9, popular: true },
      { name: "سه‌ماهه نامحدود", period: "۹۰ روز", priceUsd: 22, oldPriceUsd: 27 },
      { name: "یک‌ساله نامحدود", period: "۳۶۵ روز", priceUsd: 75, oldPriceUsd: 108 },
    ],
    brandColor: "#0d6f6a",
    monogram: "Ol",
    bestseller: true,
    popular: true,
    region: "Iran",
  },
  {
    slug: "v2ray-config",
    name: "V2Ray / VLESS",
    nameFa: "وی‌تو‌ری و وی‌لس",
    category: "vpn",
    shortFa: "کانفیگ V2Ray، VLESS و Reality",
    taglineFa: "پیشرفته‌ترین پروتکل ضدفیلتر",
    descriptionFa:
      "کانفیگ‌های V2Ray با پروتکل VLESS + Reality یا VMESS + WS + TLS، تست‌شده برای کاربران ایرانی. مناسب همه دیوایس‌ها (V2RayN، V2Box، Streisand، Hiddify).",
    features: [
      "VLESS + Reality",
      "VMESS + WebSocket + TLS",
      "Trojan",
      "سرور آلمان، فنلاند، ترکیه",
      "تست‌شده روی همه اپراتورها",
    ],
    tariffs: [
      { name: "یک‌ماهه ۳۰GB", period: "۳۰ روز", priceUsd: 4 },
      { name: "یک‌ماهه ۱۰۰GB", period: "۳۰ روز", priceUsd: 8, popular: true },
      { name: "یک‌ماهه نامحدود", period: "۳۰ روز", priceUsd: 14 },
      { name: "سه‌ماهه ۳۰۰GB", period: "۹۰ روز", priceUsd: 22, oldPriceUsd: 24 },
    ],
    brandColor: "#1a4a6e",
    monogram: "V2",
    bestseller: true,
    popular: true,
    region: "Iran",
  },
  {
    slug: "wireguard-iran",
    name: "WireGuard",
    nameFa: "وایرگارد",
    category: "vpn",
    shortFa: "پروتکل WireGuard مدرن و سریع",
    taglineFa: "پایداری بالا برای کار و گیمینگ",
    descriptionFa:
      "WireGuard سبک‌ترین و سریع‌ترین پروتکل وی‌پی‌ان مدرن است. کانفیگ‌های اختصاصی ما برای ایران بهینه شده‌اند.",
    features: ["سرعت بالا", "پینگ پایین", "اپ Native", "MultiHop"],
    tariffs: [
      { name: "یک‌ماهه نامحدود", period: "۳۰ روز", priceUsd: 8, popular: true },
      { name: "سه‌ماهه نامحدود", period: "۹۰ روز", priceUsd: 22 },
    ],
    brandColor: "#a83a3a",
    monogram: "Wg",
    region: "Iran",
  },
  {
    slug: "expressvpn",
    name: "ExpressVPN",
    nameFa: "اکسپرس‌وی‌پی‌ان",
    category: "vpn",
    shortFa: "محبوب‌ترین وی‌پی‌ان تجاری جهان",
    taglineFa: "اکانت اختصاصی روی ایمیل شما",
    descriptionFa:
      "ExpressVPN یکی از معتبرترین وی‌پی‌ان‌های تجاری جهان است. اکانت روی ایمیل شما فعال می‌شود.",
    features: ["+۹۴ کشور", "Lightway protocol", "اکانت اختصاصی"],
    tariffs: [
      { name: "یک‌ساله", period: "۳۶۵ روز", priceUsd: 80, popular: true },
      { name: "دوساله", period: "۷۳۰ روز", priceUsd: 140 },
    ],
    brandColor: "#fa3a3a",
    monogram: "Ex",
    region: "Global",
  },
  {
    slug: "nordvpn",
    name: "NordVPN",
    nameFa: "نوردوی‌پی‌ان",
    category: "vpn",
    shortFa: "وی‌پی‌ان معتبر با Threat Protection",
    taglineFa: "+۶۰۰۰ سرور در ۶۰ کشور",
    descriptionFa:
      "NordVPN امکانات امنیتی پیشرفته مثل Threat Protection، Meshnet و Double VPN دارد. اکانت اختصاصی روی ایمیل شما.",
    features: ["+۶۰۰۰ سرور", "Threat Protection", "Meshnet", "Double VPN"],
    tariffs: [
      { name: "یک‌ساله Plus", period: "۳۶۵ روز", priceUsd: 70, popular: true },
      { name: "دوساله Plus", period: "۷۳۰ روز", priceUsd: 120 },
    ],
    brandColor: "#1a3aea",
    monogram: "Nv",
    region: "Global",
  },
  {
    slug: "protonvpn",
    name: "Proton VPN Plus",
    nameFa: "پروتون وی‌پی‌ان",
    category: "vpn",
    shortFa: "وی‌پی‌ان متن‌باز سوئیسی",
    taglineFa: "حریم خصوصی و قانون سوئیس",
    descriptionFa:
      "Proton VPN از سازندگان Proton Mail، یکی از خصوصی‌ترین وی‌پی‌ان‌های جهان است. اکانت روی ایمیل شما.",
    features: ["NetShield", "Stealth Protocol", "Tor over VPN", "اپ متن‌باز"],
    tariffs: [
      { name: "یک‌ساله Plus", period: "۳۶۵ روز", priceUsd: 65, popular: true },
      { name: "دوساله Plus", period: "۷۳۰ روز", priceUsd: 110 },
    ],
    brandColor: "#6a3aea",
    monogram: "Pt",
    region: "Global",
  },
  {
    slug: "mullvad",
    name: "Mullvad VPN",
    nameFa: "مولواد",
    category: "vpn",
    shortFa: "حداکثر حریم خصوصی، بدون ایمیل",
    taglineFa: "تنها وی‌پی‌ان بدون نیاز به اکانت",
    descriptionFa:
      "Mullvad تنها VPN جهان است که حتی به ایمیل نیاز ندارد. شما فقط یک شماره اکانت می‌گیرید. ما این شماره را برایتان شارژ می‌کنیم.",
    features: ["بدون ایمیل", "WireGuard", "ضد فینگرپرینت", "پرداخت ناشناس"],
    tariffs: [
      { name: "یک‌ماهه", period: "۳۰ روز", priceUsd: 9, popular: true },
      { name: "یک‌ساله", period: "۳۶۵ روز", priceUsd: 95 },
    ],
    brandColor: "#fac01a",
    brandTextColor: "#000",
    monogram: "Ml",
    region: "Global",
  },

  // ===== PROXY =====
  {
    slug: "residential-proxy",
    name: "Residential Proxy",
    nameFa: "پراکسی رزیدنشال",
    category: "proxy",
    shortFa: "IP خانگی واقعی برای کارهای تخصصی",
    taglineFa: "+۱۰۰ کشور، چرخشی یا ثابت",
    descriptionFa:
      "پراکسی Residential از IP کاربران واقعی استفاده می‌کند. مناسب اسکریپت‌نویسی، Sneaker Bot، اسکراپ، مدیریت حساب و SEO.",
    features: ["IP خانگی واقعی", "+۱۰۰ کشور", "چرخشی یا چسبنده", "HTTP/SOCKS5"],
    tariffs: [
      { name: "بسته ۲ گیگ", period: "۳۰ روز", priceUsd: 18 },
      { name: "بسته ۱۰ گیگ", period: "۳۰ روز", priceUsd: 60, popular: true },
      { name: "بسته ۵۰ گیگ", period: "۹۰ روز", priceUsd: 240 },
    ],
    brandColor: "#404a8b",
    monogram: "Re",
    region: "Global",
  },
  {
    slug: "mobile-proxy",
    name: "Mobile Proxy 4G",
    nameFa: "پراکسی موبایل ۴G",
    category: "proxy",
    shortFa: "IP موبایل واقعی، شارژ شده",
    taglineFa: "بهترین گزینه برای حساب‌های اجتماعی",
    descriptionFa:
      "پراکسی Mobile روی شبکه ۴G/۵G سیم‌کارت‌های واقعی است. بهترین گزینه برای مدیریت حساب‌های اینستاگرام، تیک‌تاک و توییتر.",
    features: ["IP موبایل ۴G/۵G", "Rotating یا Sticky", "اپراتورهای واقعی", "تغییر IP در درخواست"],
    tariffs: [
      { name: "اشتراک ۱ پورت ماهانه", period: "۳۰ روز", priceUsd: 65, popular: true },
      { name: "اشتراک ۵ پورت ماهانه", period: "۳۰ روز", priceUsd: 280 },
    ],
    brandColor: "#3a8a4a",
    monogram: "Mo",
    region: "Global",
  },
  {
    slug: "datacenter-proxy",
    name: "Datacenter Proxy",
    nameFa: "پراکسی دیتاسنتر",
    category: "proxy",
    shortFa: "IP دیتاسنتر، سرعت بالا، قیمت پایین",
    taglineFa: "مناسب وب‌اسکراپ و SEO",
    descriptionFa:
      "پراکسی Datacenter سریع‌ترین و ارزان‌ترین گزینه است. مناسب کارهایی که نیاز به IP خاصی ندارند ولی به سرعت بالا.",
    features: ["سرعت Gbps", "قیمت پایین", "پایداری بالا", "IPv4 و IPv6"],
    tariffs: [
      { name: "۱۰ IP ماهانه", period: "۳۰ روز", priceUsd: 22, popular: true },
      { name: "۵۰ IP ماهانه", period: "۳۰ روز", priceUsd: 95 },
      { name: "۱۰۰ IP ماهانه", period: "۳۰ روز", priceUsd: 175 },
    ],
    brandColor: "#1a4a6e",
    monogram: "Dc",
    region: "Global",
  },

  // ===== GIFT CARD =====
  {
    slug: "apple-gift-card",
    name: "Apple Gift Card",
    nameFa: "گیفت کارت اپل",
    category: "gift-card",
    shortFa: "شارژ App Store، iCloud و iTunes",
    taglineFa: "گیفت کارت ریجن آمریکا، اروپا و ترکیه",
    descriptionFa:
      "گیفت کارت Apple برای شارژ Apple ID، خرید از App Store، iTunes، iCloud+ و Apple Music. ریجن‌های مختلف موجود است.",
    features: ["ریجن آمریکا، انگلستان، ترکیه، آلمان", "ارسال کد در ۵ دقیقه", "اعتبار دائمی", "بدون انقضا"],
    tariffs: [
      { name: "گیفت ۱۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 12 },
      { name: "گیفت ۲۵ دلار آمریکا", period: "بدون انقضا", priceUsd: 28, popular: true },
      { name: "گیفت ۵۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 55 },
      { name: "گیفت ۱۰۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 108 },
    ],
    brandColor: "#0a0a0a",
    monogram: "Ap",
    bestseller: true,
    region: "USA / EU / TR",
  },
  {
    slug: "google-play-gift-card",
    name: "Google Play",
    nameFa: "گیفت کارت گوگل پلی",
    category: "gift-card",
    shortFa: "شارژ Google Play و YouTube Premium",
    taglineFa: "ریجن آمریکا و ترکیه",
    descriptionFa:
      "گیفت کارت Google Play برای خرید اپ، گیم و شارژ یوتیوب پریمیوم.",
    features: ["ریجن آمریکا و ترکیه", "ارسال کد فوری", "بدون انقضا"],
    tariffs: [
      { name: "گیفت ۱۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 12 },
      { name: "گیفت ۲۵ دلار آمریکا", period: "بدون انقضا", priceUsd: 28, popular: true },
      { name: "گیفت ۵۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 55 },
    ],
    brandColor: "#3a8a4a",
    monogram: "Gp",
    region: "USA / TR",
  },
  {
    slug: "steam-wallet",
    name: "Steam Wallet",
    nameFa: "شارژ استیم",
    category: "gift-card",
    shortFa: "شارژ کیف پول Steam برای خرید بازی",
    taglineFa: "Steam، Discord و Bot Games",
    descriptionFa:
      "شارژ کیف پول Steam با ریجن‌های مختلف برای خرید بازی، DLC و آیتم.",
    features: ["ریجن آمریکا، ارجستان، ترکیه", "ارسال کد فوری", "Trade Items"],
    tariffs: [
      { name: "شارژ ۱۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 12 },
      { name: "شارژ ۲۵ دلار آمریکا", period: "بدون انقضا", priceUsd: 28, popular: true },
      { name: "شارژ ۵۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 55 },
    ],
    brandColor: "#1a3a4a",
    monogram: "St",
    region: "USA / AR / TR",
  },
  {
    slug: "playstation-wallet",
    name: "PlayStation Network",
    nameFa: "شارژ پلی‌استیشن",
    category: "gift-card",
    shortFa: "شارژ کیف پول PSN",
    taglineFa: "PS Plus و خرید بازی",
    descriptionFa: "شارژ کیف پول PlayStation Network با ریجن‌های آمریکا و ترکیه.",
    features: ["ریجن آمریکا و ترکیه", "PS Plus Extra/Deluxe", "خرید بازی"],
    tariffs: [
      { name: "شارژ ۱۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 12 },
      { name: "شارژ ۲۵ دلار آمریکا", period: "بدون انقضا", priceUsd: 28, popular: true },
      { name: "شارژ ۵۰ دلار آمریکا", period: "بدون انقضا", priceUsd: 55 },
    ],
    brandColor: "#0a3aea",
    monogram: "Ps",
    region: "USA / TR",
  },

  // ===== SUBSCRIPTION =====
  {
    slug: "spotify-premium",
    name: "Spotify Premium",
    nameFa: "اسپاتیفای پریمیوم",
    category: "subscription",
    shortFa: "اشتراک نامحدود موسیقی",
    taglineFa: "روی اکانت شخصی شما",
    descriptionFa:
      "اشتراک Spotify Premium روی اکانت شخصی شما فعال می‌شود. بدون تبلیغ، دانلود آفلاین و کیفیت بالا.",
    features: ["بدون تبلیغ", "دانلود آفلاین", "کیفیت Very High", "هر دستگاهی"],
    tariffs: [
      { name: "یک‌ماهه", period: "۳۰ روز", priceUsd: 5, popular: true },
      { name: "سه‌ماهه", period: "۹۰ روز", priceUsd: 14 },
      { name: "یک‌ساله", period: "۳۶۵ روز", priceUsd: 50, oldPriceUsd: 60 },
    ],
    brandColor: "#1ed760",
    brandTextColor: "#000",
    monogram: "Sp",
    bestseller: true,
    popular: true,
    region: "Global",
  },
  {
    slug: "youtube-premium",
    name: "YouTube Premium",
    nameFa: "یوتیوب پریمیوم",
    category: "subscription",
    shortFa: "تماشای یوتیوب بدون تبلیغ + Music",
    taglineFa: "روی اکانت گوگل شما",
    descriptionFa:
      "اشتراک YouTube Premium بدون تبلیغ، دانلود آفلاین و دسترسی به YouTube Music.",
    features: ["بدون تبلیغ", "دانلود آفلاین", "Background Play", "YouTube Music"],
    tariffs: [
      { name: "یک‌ماهه", period: "۳۰ روز", priceUsd: 6, popular: true },
      { name: "سه‌ماهه", period: "۹۰ روز", priceUsd: 16 },
      { name: "یک‌ساله", period: "۳۶۵ روز", priceUsd: 60, oldPriceUsd: 72 },
    ],
    brandColor: "#fa1a1a",
    monogram: "Yt",
    bestseller: true,
    region: "Global",
  },
  {
    slug: "netflix-premium",
    name: "Netflix Premium",
    nameFa: "نتفلیکس پریمیوم",
    category: "subscription",
    shortFa: "اشتراک Netflix Premium 4K",
    taglineFa: "اشتراک شخصی روی پروفایل شما",
    descriptionFa: "اشتراک Netflix Premium با کیفیت 4K HDR، ۴ پروفایل همزمان.",
    features: ["کیفیت 4K HDR", "۴ صفحه همزمان", "دانلود آفلاین", "Spatial Audio"],
    tariffs: [
      { name: "یک‌ماهه", period: "۳۰ روز", priceUsd: 16 },
      { name: "سه‌ماهه", period: "۹۰ روز", priceUsd: 45, popular: true },
      { name: "یک‌ساله", period: "۳۶۵ روز", priceUsd: 165 },
    ],
    brandColor: "#e50914",
    monogram: "Nx",
    bestseller: true,
    region: "Global",
  },
  {
    slug: "discord-nitro",
    name: "Discord Nitro",
    nameFa: "دیسکورد نیترو",
    category: "subscription",
    shortFa: "ارتقای کامل Discord",
    taglineFa: "آپلود ۵۰۰MB، آواتار انیمیشنی، Server Boost",
    descriptionFa:
      "Discord Nitro Pro شامل آپلود ۵۰۰MB، آواتار انیمیشنی، استیکرهای پریمیوم و ۲ Boost سرور است.",
    features: ["آپلود ۵۰۰MB", "آواتار GIF", "۲ Boost", "Custom Emoji"],
    tariffs: [
      { name: "یک‌ماهه", period: "۳۰ روز", priceUsd: 12, popular: true },
      { name: "یک‌ساله", period: "۳۶۵ روز", priceUsd: 100, oldPriceUsd: 120 },
    ],
    brandColor: "#5865f2",
    monogram: "Ds",
    region: "Global",
  },
  {
    slug: "telegram-premium",
    name: "Telegram Premium",
    nameFa: "تلگرام پریمیوم",
    category: "subscription",
    shortFa: "ارتقای رسمی تلگرام",
    taglineFa: "آپلود ۴GB، استیکرهای پریمیوم",
    descriptionFa: "اشتراک Telegram Premium با آپلود ۴GB، سرعت دانلود نامحدود و امکانات اختصاصی.",
    features: ["آپلود ۴GB", "بدون تبلیغ", "Stickers Premium", "Reactions"],
    tariffs: [
      { name: "سه‌ماهه", period: "۹۰ روز", priceUsd: 12, popular: true },
      { name: "شش‌ماهه", period: "۱۸۰ روز", priceUsd: 22 },
      { name: "یک‌ساله", period: "۳۶۵ روز", priceUsd: 38 },
    ],
    brandColor: "#1aa8e0",
    monogram: "Tg",
    bestseller: true,
    region: "Global",
  },
];

// Merge curated (hand-written, top-72) + extended (auto-imported from license-market).
// Curated takes precedence if a slug appears in both (CURATED_SERVICES first).
const _curatedSlugs = new Set(CURATED_SERVICES.map((s) => s.slug));
export const SERVICES: Service[] = [
  ...CURATED_SERVICES,
  ...EXTENDED_SERVICES.filter((s) => !_curatedSlugs.has(s.slug)),
];

export const SERVICE_BY_SLUG: Record<string, Service> = Object.fromEntries(
  SERVICES.map((s) => [s.slug, s])
);

export function servicesByCategory(category: string) {
  return SERVICES.filter((s) => s.category === category);
}
